### PR TITLE
Fixes #6604: Split the html documentation to improve readability and navigability

### PR DESCRIPTION
**Pull request by amousset**
https://www.rudder-project.org/redmine/issues/6604

### CODE REVIEW

**Comment by amousset** [comment]
Draft for now

**Comment by jooooooon** [comment]
What's the status of this PR, @amousset ?

**Comment by amousset** [comment]
The build with docbook webhelp is [functional](https://www.rudder-project.org/redmine/attachments/download/940/Screenshot%20from%202015-08-17%2010-59-34.png).

**Comment by jooooooon** [comment]
Oh my god, this looks **amazing** !!!!! :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1:

So, just to be sure, this branch is no longer a draft/WIP, it is ready to be merged? If so, please wait, I would like to consider if we can put this on existing versions to improve the current documentation.

**Comment by jooooooon** [comment]
Actually, I have one question. I note that at the top of the screen, there is the document title (Rudder documentation) and the section title (Configuration management in this screenshot). However, they appear at the exact same size, which I find confusing.

Can you easily hack this so that the second one is smaller (ie, H1 and H2)? If it's not easy, don't worry. This is better than anything ever before... :)

**Comment by amousset** [comment]
This still needs some polishing (keywords are not highlighted, the search does not work, the code and warning blocks are not styled correctly, ...).

We can easily put this on existing versions as it does not require any changes in the documentation (only a new target in the makefile).

**Comment by amousset** [comment]
PR updated with fixed code and admonition blocks, keyword highlighting, and second title smaller. Search is still missing.

**Comment by amousset** [comment]
PR updated with docbook debian path and hidden search tab. Closing and targeting to 2.10.

**Pull request closed without merging**
