### PR TITLE
Fixes #21333: Document external DB installation

### PR DESCRIPTION
**Pull request by peckpeck**
https://issues.rudder.io/issues/21333

### CODE REVIEW

**Comment by peckpeck** [comment]
PR updated with a new commit

**Comment by peckpeck** [comment]
Ready to review

**Comment by peckpeck** [comment]
PR updated with a new commit

**Comment by amousset** [comment]
There is a typo

**Comment by peckpeck** [comment]
PR updated with a new commit

**Review by amousset — APPROVED** [review]

**Pull request merged**
