### PR TITLE
Fixes #20611: Some screenshots in documentation are too old

### PR DESCRIPTION
**Pull request by ElaadF**
https://issues.rudder.io/issues/20611
We need to resize some screeshots I think... :sob:

### CODE REVIEW

**Comment by amousset** [comment]
Can you also run `make optipng` in the repo to improve image size?

**Comment by ElaadF** [comment]
PR updated with a new commit

**Comment by ElaadF** [comment]
PR updated with a new commit

**Comment by ElaadF** [comment]
PR updated with a new commit

**Comment by ElaadF** [comment]
PR rebased

**Review by amousset — APPROVED** [review]

**Pull request merged**
