### PR TITLE
Fixes #8233: Create an installation section in the documentation

### PR DESCRIPTION
**Pull request by amousset**
https://www.rudder-project.org/redmine/issues/8233

### CODE REVIEW

**Comment by amousset** [comment]
Still testing the changes, do not merge for now

**Comment by jooooooon** [comment]
Still testing?

**Comment by amousset** [comment]
PR updated

**Comment by amousset** [comment]
Fixed some issues. To make this version readable, I had to change the title level at which we split the pages, which makes some other parts of the doc a bit more difficult to read. I will fix this when working on the other parts of the docs.

**Comment by jooooooon** [comment]
This is a huge improvement. It just reads naturally now, whereas before you had to go searching to find the right contents.

**Comment by jooooooon** [comment]
I realise that I should have let you merge + upmerge this. Sorry, I clicked a bit too hasitly. Can you do the up-merge manually ASAP please? I fear it will be quite difficult.

**Pull request merged**
