### PR TITLE
Fixes #6762: Add a task to the ci to build the rudder man in html and man versions

### PR DESCRIPTION
**Pull request by amousset**
https://www.rudder-project.org/redmine/issues/6762

### CODE REVIEW

**Comment by amousset** [comment]
Please do not merge for now, WIP

**Comment by amousset** [comment]
PR updated

**Comment by amousset** [comment]
Ready for review now.

**Comment by amousset** [comment]
PR updated

**Comment by peckpeck** [comment]
OK, merging

**Pull request merged**
