### PR TITLE
Explain how to get node acceptation/deletion time

### PR DESCRIPTION
**Pull request by fanf**

### CODE REVIEW

**Comment by amousset** [comment]
I'm not sure it suits into Rudder by example, it is not normal behaviour to have to connect to the postgreSQL server to get basic node information, it is more a workaround than an example. It may be better inside the FAQ?

**Comment by fanf** [comment]
@amousset it's also ok for me if we had a "tip & tricks" documentation, whose goal is explicitly to give workaround, tips, tricks and other little information about Rudder usage without the "guide line" aspect you seems to put behing "Rudder by example" (and that suits me)

**Comment by fanf** [comment]
Update: in fact, rudder by example was thought to be a "example of rudder best practices". Clearly, that hacky script is not one of them. 

So we propose to update Rudder by example to have two parts: "best practices" and "hacky tips and tricks when you face a situation where you need to get a workaround"

**Comment by fanf** [comment]
Create a paragraph in `Usage > Tips` and put it there.

**Comment by fanf** [comment]
This is not accurate anymore and should use `fact-repository`, with something like: 

```
% cd /var/rudder/fact-repository/nodes
% git log --all --full-history -- accepted/348048fb-0fda-470c-a2ea-c4d7f91eb19c.json | grep deleted
```

**Pull request closed without merging**
