### PR TITLE
Fixes #12981: Improve new doc interface

### PR DESCRIPTION
**Pull request by RaphaelGauthier**
https://www.rudder-project.org/redmine/issues/12981

### CODE REVIEW

**Comment by amousset** [comment]
THIS IS GREAT!

**Comment by amousset** [comment]
menu
The is a small alignment pb (on firefox 60).

**Comment by amousset** [comment]
Could you also make the menu a bit more compact. It is ok for small guides, but we have to scroll too much for refece manual.

**Comment by RaphaelGauthier** [comment]
Commit modified

**Pull request merged**
