### PR TITLE
Fixes #16984: Improve accessibility of documentation site's menu

### PR DESCRIPTION
**Pull request by RaphaelGauthier**
https://issues.rudder.io/issues/16984

### CODE REVIEW

**Comment by amousset** [comment]
Could you add a screenshot for easier review?

**Comment by RaphaelGauthier** [comment]
> Could you add a screenshot for easier review?

doc-menu-v2
doc-menu-v2-b

**Comment by RaphaelGauthier** [comment]
Commit modified

**Comment by RaphaelGauthier** [comment]
Commit modified

**Pull request merged**
