### PR TITLE
Fixes #19036: Incorrect option in pg_restore for archive 

### PR DESCRIPTION
**Pull request by fanf**
https://issues.rudder.io/issues/19036

### CODE REVIEW

**Comment by fanf** [comment]
PR updated with a new commit

**Comment by fanf** [comment]
PR updated with a new commit

**Comment by fanf** [comment]
PR updated with a new commit

**Review by VinceMacBuche — APPROVED** [review]

**Review by ncharles — APPROVED** [review]

**Comment by fanf** [comment]
OK, squash merging this PR

**Pull request merged**
